// Mocks generated by Mockito 5.4.5 from annotations
// in repondo/test/features/despensa/mocks/despensa_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:repondo/core/result/result.dart' as _i4;
import 'package:repondo/features/despensa/application/facades/despensa_facade.dart'
    as _i2;
import 'package:repondo/features/despensa/application/usecases/create_despensa_use_case.dart'
    as _i9;
import 'package:repondo/features/despensa/domain/entities/despensa.dart' as _i5;
import 'package:repondo/features/despensa/domain/exceptions/despensa_exception.dart'
    as _i6;
import 'package:repondo/features/despensa/domain/params/create_despensa_params.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DespensaFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockDespensaFacade extends _i1.Mock implements _i2.DespensaFacade {
  MockDespensaFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.Despensa, _i6.DespensaException>> createDespensa({
    required _i7.CreateDespensaParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDespensa, [], {#params: params}),
            returnValue: _i3.Future<
              _i4.Result<_i5.Despensa, _i6.DespensaException>
            >.value(
              _i8.dummyValue<_i4.Result<_i5.Despensa, _i6.DespensaException>>(
                this,
                Invocation.method(#createDespensa, [], {#params: params}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Despensa, _i6.DespensaException>>);
}

/// A class which mocks [CreateDespensaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateDespensaUseCase extends _i1.Mock
    implements _i9.CreateDespensaUseCase {
  MockCreateDespensaUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.Despensa, _i6.DespensaException>> execute({
    required _i7.CreateDespensaParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#params: params}),
            returnValue: _i3.Future<
              _i4.Result<_i5.Despensa, _i6.DespensaException>
            >.value(
              _i8.dummyValue<_i4.Result<_i5.Despensa, _i6.DespensaException>>(
                this,
                Invocation.method(#execute, [], {#params: params}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Despensa, _i6.DespensaException>>);
}
