// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcQoJhoYNz4u71d-K4w20ufixEYO654Vc',
    appId: '1:355943040604:android:f37226eaf6b7e536c74899',
    messagingSenderId: '355943040604',
    projectId: 'repondo-22eca',
    storageBucket: 'repondo-22eca.firebasestorage.app',
  );

}